### ISSUE TITLE
IDT authorize: url does not return code

### ISSUE THREAD

**Issue by brettrusnock** [idonethis/idonethis-cli#4]
Hi, I'm trying to set up the idonethis CLI. When I run "idt authorize" it prompts me to "Enter code from this URL: https://beta.idonethis.com/oauth/authorize?client_id=bb73ffdf5672cd968bc6794d7b
43b71d610695eb39c752da08a5b006af0920d4&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.
0%3Aoob&response_type=code

When I type this URL into my web browser, I get the following error message: "Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."

Any thoughts? I'm on Windows 7. I am a ruby gems newbie, so I'm not familiar with the language. Thanks!

-Brett

**Comment by ajaykumarkannan** [comment]
Additionally, using the API token from the webpage yields this stack trace:
```
Traceback (most recent call last):
        11: from /usr/local/bin/idt:23:in `<main>'
        10: from /usr/local/bin/idt:23:in `load'
         9: from /var/lib/gems/2.5.0/gems/idonethis-official-cli-0.1.3/bin/idt:5:in `<top (required)>'
         8: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
         7: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         6: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         5: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         4: from /var/lib/gems/2.5.0/gems/idonethis-official-cli-0.1.3/lib/idonethis_cli/cli.rb:22:in `authorize'
         3: from /var/lib/gems/2.5.0/gems/idonethis-official-cli-0.1.3/lib/idonethis_cli/client/auth.rb:19:in `oauth2_token'
         2: from /var/lib/gems/2.5.0/gems/oauth2-1.4.1/lib/oauth2/strategy/auth_code.rb:30:in `get_token'
         1: from /var/lib/gems/2.5.0/gems/oauth2-1.4.1/lib/oauth2/client.rb:146:in `get_token'
/var/lib/gems/2.5.0/gems/oauth2-1.4.1/lib/oauth2/client.rb:119:in `request': invalid_grant: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. (OAuth2::Error)
{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}
```
